name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t pinakastra-web .
    
    - name: Push Docker image to DockerHub
      run: |
        docker tag pinakastra-web ${{ secrets.DOCKER_USERNAME }}/pinakastra-web:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/pinakastra-web:latest

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl rollout status deployment/pinakastra-web
